### ISSUE TITLE
Allow copy code to clipboard. 

### ISSUE THREAD

**Issue by fakoua** [react-syntax-highlighter/react-syntax-highlighter#239]
Hi,
I can't see allowCopy property, it's a very useful feature if not supported. 
Thanks

**Comment by ajohnson1031** [comment]
This would be a great addition.

**Comment by simmerer** [comment]
I'm using https://github.com/nkbt/react-copy-to-clipboard alongside react-syntax-highlighter with great success. Copy-to-clipboard is only useful for copying the raw input string, not the marked-up/highlighted output, so it seems like a good piece of functionality to keep separate.

**Comment by rottitime** [comment]
Could we build this in? It would be so useful

**Comment by imarkanovic** [comment]
it really depends on how you want to copy the content (indent? escape new lines?.. ). 
imo, its trivial to implement a basic copy to clipboard button, so it doesn't really make sense to fit this into the lib, when realistically you will probably want to customize the copy function anyway.
But, if you really want a basic, raw c/p, that looks nice, here's how you can implement this:

```typescript
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { materialDark } from "react-syntax-highlighter/dist/esm/styles/prism";
import { FiClipboard } from "react-icons/fi";
```

```typescript
const SyntaxHighlightedContent = ({
      language,
      content,
    }: {
      language: string;
      content: string;
    }) => {
      const handleCopy = () => {
        navigator.clipboard.writeText(content);
      };

      return (
        <div className="syntax-highlighter-container">
          <SyntaxHighlighter
            language={language}
            style={materialDark}
            customStyle={{ margin: "0", fontSize: "0.8em" }}
          >
            {content}
          </SyntaxHighlighter>
          <FiClipboard className="copy-icon" onClick={handleCopy} />
        </div>
      );
    };
```

along with css
```css
.syntax-highlighter-container {
  position: relative;
}

.copy-icon {
  position: absolute;
  top: 10px;
  right: 10px;
  cursor: pointer;
  color: #fff;
  opacity: 0.7;
  transition: opacity 0.2s;

  &:hover {
    opacity: 1;
  }
}
```

Result:
<img width="546" alt="Screenshot 2024-11-26 at 17 05 09" src="https://github.com/user-attachments/assets/af0a82c3-7869-4c97-97e2-e7586dbe7208">

**Comment by kyok0** [comment]
it really depends on how you want to copy the content (indent? escape new lines?.. ). 
imo, its trivial to implement a basic copy to clipboard button, so it doesn't really make sense to fit this into the lib, when realistically you will probably want to customize the copy function anyway.
But, if you really want a basic, raw c/p, that looks nice, here's how you can implement this:

```typescript
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { materialDark } from "react-syntax-highlighter/dist/esm/styles/prism";
import { FiClipboard } from "react-icons/fi";
```

```typescript
const SyntaxHighlightedContent = ({
      language,
      content,
    }: {
      language: string;
      content: string;
    }) => {
      const handleCopy = () => {
        navigator.clipboard.writeText(content);
      };

      return (
        <div className="syntax-highlighter-container">
          <SyntaxHighlighter
            language={language}
            style={materialDark}
            customStyle={{ margin: "0", fontSize: "0.8em" }}
          >
            {content}
          </SyntaxHighlighter>
          <FiClipboard className="copy-icon" onClick={handleCopy} />
        </div>
      );
    };
```

along with css
```css
.syntax-highlighter-container {
  position: relative;
}

.copy-icon {
  position: absolute;
  top: 10px;
  right: 10px;
  cursor: pointer;
  color: #fff;
  opacity: 0.7;
  transition: opacity 0.2s;

  &:hover {
    opacity: 1;
  }
}
```

Result:
<img width="546" alt="Screenshot 2024-11-26 at 17 05 09" src="https://github.com/user-attachments/assets/af0a82c3-7869-4c97-97e2-e7586dbe7208">
