### ISSUE TITLE
Provide a user preference responsive dark/light theme. 

### ISSUE THREAD

**Issue by dwjohnston** [react-syntax-highlighter/react-syntax-highlighter#556]
**Is your feature request related to a problem? Please describe.**

User preference queries / basing light/dark mode on system settings is pretty common these days. 

It would be nice to have a theme that works seamlessly for both dark and light themes. 

We can make use of tools like [`react-responsive`](https://www.npmjs.com/package/react-responsive) to choose a theme. 

eg:

```tsx
export default function A() {

    const isDarkMode = useMediaQuery({ query: "(prefers-color-scheme: dark)" })

    return <SyntaxHighlighter language="javascript" style={isDarkMode ? tomorrowNight : github}>
        {`function foo() {
    console.log("hello");
}`}
    </SyntaxHighlighter>
    
}
```

The problem with this when it comes on server side rendering. Server side  - the server has no idea what the user preference is - and so SSR the light theme will always be used. 

I have a reproduction of this issue here: https://github.com/dwjohnston/highlighting-ssr

This can be resolved by doing a client side 'wait for second render': 

```tsx
export default function A() {

  const isDarkMode = useMediaQuery({ query: "(prefers-color-scheme: dark)" })

  const [ready, setReady] = useState(false); 

  useEffect(() => {
    setReady(true); 
  }, []);

  if(!ready){
    return null;
  }

  return <div>
    <SyntaxHighlighter language="javascript" style={isDarkMode ? tomorrowNight : github}>
      {`function foo() {
    console.log("hello");
}`}
    </SyntaxHighlighter>
  </div>
}
```

But the problem with this that you may lose some,  SEO advantages, you'll have a layout pop, etc. 

**Describe the solution you'd like**
A single theme that works for light and dark preference. 

**Describe alternatives you've considered**

Failing that - a theme that is 'no style' - just inheriting the color and background. That way we'll still get a style pop, but it's not as jarring as a sudden white to black. 

**Additional context**

See these threads on react responsive relating to user preference and SSR: 

https://github.com/yocontra/react-responsive/issues/319

https://github.com/yocontra/react-responsive/issues/204

**Comment by maddrag0n** [comment]
SSR you can use the `Sec-CH-Prefers-Color-Scheme` HTTP header which

- works for Chrome: https://chromestatus.com/feature/5642300464037888
- feature request in WebKit: https://lists.webkit.org/pipermail/webkit-dev/2021-May/031856.html
- feature request in Mozilla: https://github.com/mozilla/standards-positions/issues/526

**Comment by dwjohnston** [comment]
Here's a 'no theme' theme you can use: 

``` typescript
const noTheme = {
    "hljs": {
        "display": "block",
        "overflowX": "auto",
        "padding": "0.5em",
        "color": "inherit",
        "background": "inherit",
    },
    "hljs-comment": {
        "color": "inherit",
        "fontStyle": "italic"
    },
    "hljs-quote": {
        "color": "inherit",
        "fontStyle": "italic"
    },
    "hljs-keyword": {
        "color": "inherit",
        "fontWeight": "bold"
    },
    "hljs-selector-tag": {
        "color": "inherit",
        "fontWeight": "bold"
    },
    "hljs-subst": {
        "color": "inherit",
        "fontWeight": "normal"
    },
    "hljs-number": {
        "color": "inherit",
    },
    "hljs-literal": {
        "color": "inherit",
    },
    "hljs-variable": {
        "color": "inherit",
    },
    "hljs-template-variable": {
        "color": "inherit",
    },
    "hljs-tag .hljs-attr": {
        "color": "inherit",
    },
    "hljs-string": {
        "color": "inherit",
    },
    "hljs-doctag": {
        "color": "inherit",
    },
    "hljs-title": {
        "color": "inherit",
        "fontWeight": "bold"
    },
    "hljs-section": {
        "color": "inherit",
        "fontWeight": "bold"
    },
    "hljs-selector-id": {
        "color": "inherit",
        "fontWeight": "bold"
    },
    "hljs-type": {
        "color": "inherit",
        "fontWeight": "bold"
    },
    "hljs-class .hljs-title": {
        "color": "inherit",
        "fontWeight": "bold"
    },
    "hljs-tag": {
        "color": "inherit",
        "fontWeight": "normal"
    },
    "hljs-name": {
        "color": "inherit",
        "fontWeight": "normal"
    },
    "hljs-attribute": {
        "color": "inherit",
        "fontWeight": "normal"
    },
    "hljs-regexp": {
        "color": "inherit",
    },
    "hljs-link": {
        "color": "inherit",
    },
    "hljs-symbol": {
        "color": "inherit",
    },
    "hljs-bullet": {
        "color": "inherit",
    },
    "hljs-built_in": {
        "color": "inherit",
    },
    "hljs-builtin-name": {
        "color": "inherit",
    },
    "hljs-meta": {
        "color": "inherit",
        "fontWeight": "bold"
    },
    "hljs-deletion": {
        "background": "inherit",
    },
    "hljs-addition": {
        "background": "inherit",
    },
    "hljs-emphasis": {
        "fontStyle": "italic"
    },
    "hljs-strong": {
        "fontWeight": "bold"
    }
} as const
```

**Comment by Adrian-Zephyr-Liao** [comment]
I found a solution:
combine with `darkMode: "class"` of tailwindcss
pass `useInlineStyles: false` to the react-syntax-highlighter component
you can switch themes under SSR.
```css
/* Light mode */
:root {
  --hljs-background: #fafafa;
  --hljs-text: #383a42;
  --hljs-comment: #a0a1a7;
  --hljs-keyword: #a626a4;
  --hljs-section: #e45649;
  --hljs-literal: #0184bb;
  --hljs-string: #50a14f;
  --hljs-number: #986801;
  --hljs-symbol: #4078f2;
  --hljs-class: #c18401;
  --color-code-background: var(--hljs-background);
  --color-text-weak: #e5e7eb;
  --color-highlighted-line: rgba(0, 0, 0, 0.05);
  --color-highlighted-line-indicator: hsl(var(--primary));
  --color-inserted-line: rgba(80, 161, 79, 0.1);
  --color-deleted-line: rgba(228, 86, 73, 0.1);
}

/* Dark mode */
:root[class~="dark"] {
  --hljs-background: #282c34;
  --hljs-text: #abb2bf;
  --hljs-comment: #5c6370;
  --hljs-keyword: #c678dd;
  --hljs-section: #e06c75;
  --hljs-literal: #56b6c2;
  --hljs-string: #98c379;
  --hljs-number: #d19a66;
  --hljs-symbol: #61aeee;
  --hljs-class: #e6c07b;
  --color-code-background: var(--hljs-background);
  --color-text-weak: #374151;
  --color-highlighted-line: rgba(255, 255, 255, 0.05);
  --color-highlighted-line-indicator: hsl(var(--primary));
  --color-inserted-line: rgba(152, 195, 121, 0.1);
  --color-deleted-line: rgba(224, 108, 117, 0.1);
}

.hljs {
  color: var(--hljs-text);
  background: var(--hljs-background);
}

.hljs-comment,
.hljs-quote {
  color: var(--hljs-comment);
  font-style: italic;
}

.hljs-doctag,
.hljs-keyword,
.hljs-formula {
  color: var(--hljs-keyword);
}

.hljs-section,
.hljs-name,
.hljs-selector-tag,
.hljs-deletion,
.hljs-subst {
  color: var(--hljs-section);
}

.hljs-literal {
  color: var(--hljs-literal);
}

.hljs-string,
.hljs-regexp,
.hljs-addition,
.hljs-attribute,
.hljs-meta .hljs-string {
  color: var(--hljs-string);
}

.hljs-attr,
.hljs-variable,
.hljs-template-variable,
.hljs-type,
.hljs-selector-class,
.hljs-selector-attr,
.hljs-selector-pseudo,
.hljs-number {
  color: var(--hljs-number);
}

.hljs-symbol,
.hljs-bullet,
.hljs-link,
.hljs-meta,
.hljs-selector-id,
.hljs-title {
  color: var(--hljs-symbol);
}

.hljs-built_in,
.hljs-title.class_,
.hljs-class .hljs-title {
  color: var(--hljs-class);
}

```
